CREATE TYPE "category_kind" AS ENUM (
  'C1',
  'C2',
  'G1'
);

CREATE TYPE "requisite_type" AS ENUM (
  'Any',
  'All',
  'Co'
);

CREATE TYPE "plan_course_type" AS ENUM (
  'Normal',
  'FE',
  'Minor'
);

CREATE TYPE "mod_roles" AS ENUM (
  'lecturer',
  'staff',
  'registrar',
  'admin'
);

CREATE TABLE "ge_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "root_id" int UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "ge_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255) NOT NULL,
  "parent_id" int,
  "kind" category_kind NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
  
);

CREATE TABLE "curriculums" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" int UNIQUE,
  "name_th" varchar(255) UNIQUE NOT NULL,
  "name_en" varchar(255) UNIQUE,
  "fs_category_id" int UNIQUE NOT NULL,
  "ge_template_id" int NOT NULL,
  "ge_category_id" int UNIQUE NOT NULL,
  "fe_category_id" int UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "course_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255) NOT NULL,
  "credit" int NOT NULL DEFAULT 0,
  "kind" category_kind NOT NULL,
  "self_categorize_id" int,
  "note" varchar(255),
  "parent_id" int,
  "cross_category_id" int,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "self_categorizes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curriculum_id" int NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "self_categorize_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "self_categorize_id" int NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "curriculum_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "course_no" int NOT NULL,
  "semester" int ,
  "year" int ,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "course_requisites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curriculum_course_id" int NOT NULL,
  "related_course_no" int NOT NULL,
  "requisite_type" requisite_type NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "detail_courses" (
  "course_no" int PRIMARY KEY,
  "title_long_th" varchar(255) UNIQUE NOT NULL,
  "title_long_en" varchar(255) UNIQUE NOT NULL,
  "title_short_en" varchar(255),
  "course_desc_th" varchar(255),
  "course_desc_en" varchar(255),
  "credit" int NOT NULL DEFAULT 0,
  "prerequisite" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "plans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "student_code" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "plan_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plan_id" int NOT NULL,
  "semester" int NOT NULL,
  "year" int NOT NULL,
  "course_no" int,
  "course_type" plan_course_type NOT NULL DEFAULT 'Normal',
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "student_select_minors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_code" int NOT NULL,
  "curriculum_id" int UNIQUE NOT NULL,
  "course_no" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "Account" (
  "cmuitaccount" varchar(255) PRIMARY KEY,
  "prename" varchar(255),
  "firstname" varchar(255) NOT NULL,
  "lastname" varchar(255) NOT NULL,
  "account_type" int NOT NULL,
  "organization" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "students" (
  "student_code" int PRIMARY KEY,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "moderators" (
  "cmuitaccount" varchar(255) PRIMARY KEY,
  "role" mod_roles NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "account_types" (
  "id" int PRIMARY KEY,
  "name_th" varchar(255) UNIQUE NOT NULL,
  "name_en" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

CREATE TABLE "organizations" (
  "id" int PRIMARY KEY,
  "name_th" varchar(255) UNIQUE NOT NULL,
  "name_en" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW(),
  "updated_at" timestamp NOT NULL DEFAULT NOW(),
  "deleted_at" timestamp
);

ALTER TABLE "ge_templates" ADD FOREIGN KEY ("root_id") REFERENCES "ge_categories" ("id");

ALTER TABLE "ge_categories" ADD FOREIGN KEY ("parent_id") REFERENCES "ge_categories" ("id");

ALTER TABLE "curriculums" ADD FOREIGN KEY ("fs_category_id") REFERENCES "course_categories" ("id");

ALTER TABLE "curriculums" ADD FOREIGN KEY ("ge_template_id") REFERENCES "ge_templates" ("id");

ALTER TABLE "curriculums" ADD FOREIGN KEY ("ge_category_id") REFERENCES "course_categories" ("id");

ALTER TABLE "curriculums" ADD FOREIGN KEY ("fe_category_id") REFERENCES "course_categories" ("id");

ALTER TABLE "course_categories" ADD FOREIGN KEY ("self_categorize_id") REFERENCES "self_categorizes" ("id");

ALTER TABLE "course_categories" ADD FOREIGN KEY ("parent_id") REFERENCES "course_categories" ("id");

ALTER TABLE "course_categories" ADD FOREIGN KEY ("cross_category_id") REFERENCES "course_categories" ("id");

ALTER TABLE "self_categorizes" ADD FOREIGN KEY ("curriculum_id") REFERENCES "curriculums" ("id");

ALTER TABLE "self_categorize_members" ADD FOREIGN KEY ("self_categorize_id") REFERENCES "self_categorizes" ("id");

ALTER TABLE "curriculum_courses" ADD FOREIGN KEY ("category_id") REFERENCES "course_categories" ("id");

ALTER TABLE "curriculum_courses" ADD FOREIGN KEY ("course_no") REFERENCES "detail_courses" ("course_no");

ALTER TABLE "course_requisites" ADD FOREIGN KEY ("curriculum_course_id") REFERENCES "curriculum_courses" ("id");

ALTER TABLE "plans" ADD FOREIGN KEY ("student_code") REFERENCES "students" ("student_code");

ALTER TABLE "plan_courses" ADD FOREIGN KEY ("plan_id") REFERENCES "plans" ("id");

ALTER TABLE "plan_courses" ADD FOREIGN KEY ("course_no") REFERENCES "detail_courses" ("course_no");

ALTER TABLE "student_select_minors" ADD FOREIGN KEY ("student_code") REFERENCES "students" ("student_code");

ALTER TABLE "student_select_minors" ADD FOREIGN KEY ("curriculum_id") REFERENCES "curriculums" ("id");

ALTER TABLE "student_select_minors" ADD FOREIGN KEY ("course_no") REFERENCES "detail_courses" ("course_no");

ALTER TABLE "Account" ADD FOREIGN KEY ("account_type") REFERENCES "account_types" ("id");

ALTER TABLE "Account" ADD FOREIGN KEY ("organization") REFERENCES "organizations" ("id");
